# content of contacts-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts
  labels:
    app: contacts
    service: contactsapi
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: contacts
      service: contactsapi
  template:
    metadata:
      labels:
        app: contacts
        service: contactsapi
    spec:
      automountServiceAccountToken: false
      containers:
        - name: contacts
          resources:
            requests:
              memory: '64Mi'
              cpu: '100m'
            limits:
              memory: '256Mi'
              cpu: '500m'
          image: ghcr.io/azuredevcollege/adc-contacts-api:3.0
          env:
            - name: ConnectionStrings__DefaultConnectionString
              value: "Server=tcp:contacts-db,1433;Initial Catalog=contactsdb;Persist Security Info=False;User ID=sa;Password=Ch@ngeMe!23;MultipleActiveResultSets=False;Encrypt=False;TrustServerCertificate=True;Connection Timeout=30;"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: contacts
  labels:
    app: contacts
    service: contactsapi
spec:
  type: ClusterIP
  selector:
    app: contacts
    service: contactsapi
  ports:
    - port: 8080
      targetPort: 5000
